### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [tobihrbr/hekto#2]
Hi,

I'm a member of the Node.js Security WG and we received a report regarding a security issue with this module.

We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by herber** [comment]
Hi, 

I am the creator of this project and have not received an e-mail from you, are you sure you had the correct address?

This is a relatively old project(the last commit was 10 months ago). Thank you for making me aware of security issues. I will rewrite the whole codebase asap, since it is pretty outdated!

**Comment by lirantal** [comment]
Thanks for the prompt reply!
I used the e-mail address that I could find from your account on npm: https://www.npmjs.com/~tobi~
If there's another e-mail address I should use for the invite please let me know.

Can you please join the conversation on the Hacker1 platform to collaborate with the bug hunter about this report? You should've received an invite in your inbox

**Comment by AdolfHitler881945** [comment]
Scheiß Jude

**Comment by herber** [comment]
Could you please send the invite to tobihrbr@gmail.com

**Comment by lirantal** [comment]
Sent.
